### PR TITLE
improved send command

### PR DESCRIPTION
**Pull request by hmueller01**
Make send more flexible to accept unitCode as number as well as bit code, added help output.

### CODE REVIEW

**Comment by hmueller01** [comment]
Is no one willing to commit my pull request to master?

**Comment by elliots** [comment]
Sorry @hmueller01 noone is really around here anymore. I can merge if you don't think it'll cause problems for other people?

**Comment by hmueller01** [comment]
No, it should not. 100% compatible. Gives the extra option/possibility to use bit matrix or number. Please merge. Tx.

**Comment by ichbestimmtnicht** [comment]
Maybe you should try it with an email at support@ninjablocks.com

**Comment by elliots** [comment]
If that email address still existed, it would probably be me checking it ;)

I'll merge.

**Pull request merged**
