### PR TITLE
Added optional pulse-length argument to RFSniffer and the executables to gitignore

### PR DESCRIPTION
**Pull request by rotv**

### CODE REVIEW

**Comment by elliots** [comment]
Should I assume this works as expected and won't cause problems? (I have no idea how to run this) 

:)

**Comment by rotv** [comment]
It works on my computer ;)

`sudo ./RFSniffer` is the normal way, I've added `sudo ./RFSniffer <pulseLength>`, e.g. `sudo ./RFSniffer 150` (both ways are still supported)

**Comment by rotv** [comment]
I figured at would simplify quite a lot for users to easily be able to test/specify different pulse lengths without having to rewrite and recompile the code.

**Comment by rotv** [comment]
Any taker for merging this?

**Comment by elliots** [comment]
Apologies, thought I already merged this.

**Pull request merged**
