### PR TITLE
#54 RFSniffer didn't flush output

### PR DESCRIPTION
**Pull request by chrisEff**

### CODE REVIEW

**Comment by chrisEff** [comment]
Hey guys,
I'd REALLY appreciate if someone could spare a minute or two to review (and hopefully merge) this.
Thanks,
Chris

**Comment by elliots** [comment]
Could it cause problems for other people? If not, all good i'll merge.

**Comment by chrisEff** [comment]
Well, I can't think of any way that it could. How about you?

**Comment by elliots** [comment]
Ok.

**Pull request merged**
