### PR TITLE
A much needed improvement of rc-switch (contains bug fixes and additional devices)

### PR DESCRIPTION
**Pull request by rotv**
This change adds the original rc-switch repo (from where rc-switch was _copied_ three years ago) as a submodule. Hence this PR will 'upgrade' rc-switch to support additional devices and keep the connection for the future, i.e. any future fixes and improvements can easily be incorporated into 433Utils by simply changing which commit of rc-switch we want 433Utils to use.

### CODE REVIEW

**Comment by rotv** [comment]
@elliots, since you've been active quite recently, can you take a look at this PR?

**Comment by rotv** [comment]
@jonseymour Would you care to take a look at this PR?

**Comment by rotv** [comment]
Anyone?

**Comment by elliots** [comment]
I'm happy to merge, but I haven't/can't test it. Maybe if someone else can test it out? Also, apologies I don't seem to be getting notifications.

**Comment by justy** [comment]
@rotv I appreciate the effort- I can test this with some RF433 HW this week.

**Comment by roidayan** [comment]
Hi, I verified codesend and RFSniffer works for me with Sunluxy RC switch with its remote control also after this pull request.

**Comment by elliots** [comment]
Good enough for me.

**Pull request merged**
